import { Feature } from '@unoff/utils'
import { Config } from '@ui-lib/types/config'
import { doSpecificMode } from '@ui-lib/stores/features'

declare const __PLUGIN__: 'fig' | 'one'
declare const __APP_VERSION__: string

const isDev = import.meta.env.MODE === 'development'

const specConfig: Record<
  string,
  {
    pluginId: string
    features: Feature<'BROWSE' | 'CREATE' | 'EDIT' | 'SEE'>[]
  }
> = {
  fig: {
    pluginId: '1063959496693642315',
    features: doSpecificMode(
      ['HELP_CHAT', 'USER_LICENSE'],
      [
        'LOCAL_PALETTES',
        'SYNC_LOCAL_STYLES',
        'SYNC_LOCAL_VARIABLES',
        'USER_PREFERENCES_SYNC_DEEP_STYLES',
        'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
        'PREVIEW_LOCK_SOURCE_COLORS',
        'PREVIEW_SCORES_WCAG_INTERVAL',
        'PREVIEW_SCORES_APCA_INTERVAL',
        'PREVIEW_FILTER_WCAG',
        'PREVIEW_FILTER_APCA',
        'PREVIEW_SHADE_REPORT',
        'DOCUMENT_PALETTE',
        'DOCUMENT_PALETTE_PROPERTIES',
        'DOCUMENT_SHEET',
        'DOCUMENT_PUSH_UPDATES',
        'VIEWS_PALETTE',
        'VIEWS_PALETTE_WITH_PROPERTIES',
        'VIEWS_SHEET',
        'SOURCE',
        'SOURCE_COOLORS_ADD',
        'SOURCE_REALTIME_COLORS_ADD',
        'SOURCE_EXPLORE_ADD',
        'SOURCE_AI_REQUEST',
        'SOURCE_IMAGE_UPLOAD',
        'SOURCE_HARMONY_BASE',
        'SOURCE_HARMONY_ADD',
        'SOURCE_EXPLORE_ADD',
        'PRESETS_MATERIAL',
        'PRESETS_MATERIAL_3',
        'PRESETS_TAILWIND',
        'PRESETS_RADIX',
        'PRESETS_UNTITLED_UI',
        'PRESETS_SPECTRUM',
        'PRESETS_SPECTRUM_NEUTRAL',
        'PRESETS_ADS',
        'PRESETS_ADS_NEUTRAL',
        'PRESETS_CARBON',
        'PRESETS_BASE',
        'PRESETS_FLUENT',
        'PRESETS_POLARIS',
        'PRESETS_CUSTOM_ADD',
        'SCALE_CONTRAST_RATIO',
        'SCALE_CHROMA',
        'SCALE_HUE',
        'THEMES',
        'THEMES_NAME',
        'THEMES_PARAMS',
        'THEMES_DESCRIPTION',
        'COLORS',
        'COLORS_HUE_SHIFTING',
        'COLORS_CHROMA_SHIFTING',
        'COLORS_ALPHA',
        'COLORS_BACKGROUND_COLOR',
        'EXPORT_STYLESHEET_SCSS',
        'EXPORT_STYLESHEET_LESS',
        'EXPORT_TAILWIND_V3',
        'EXPORT_TAILWIND_V4',
        'EXPORT_APPLE_SWIFTUI',
        'EXPORT_APPLE_UIKIT',
        'EXPORT_ANDROID_COMPOSE',
        'EXPORT_ANDROID_XML',
        'EXPORT_CSV',
        'SETTINGS_COLOR_SPACE_OKLCH',
        'SETTINGS_COLOR_SPACE_LAB',
        'SETTINGS_COLOR_SPACE_OKLAB',
        'SETTINGS_COLOR_SPACE_HSLUV',
        'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
        'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
        'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
        'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
        'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
        'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
        'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
        'SETTINGS_ALGORITHM_V1',
        'SETTINGS_ALGORITHM_V2',
        'SETTINGS_TEXT_COLORS_THEME',
        'HELP_EMAIL',
      ],
      ['INVOLVE_COMMUNITY']
    ),
  },
  one: {
    pluginId: '1532789439226122095',
    features: doSpecificMode(
      ['HELP_CHAT'],
      [
        'LOCAL_PALETTES',
        'SYNC_LOCAL_STYLES',
        'SYNC_LOCAL_VARIABLES',
        'USER_PREFERENCES_SYNC_DEEP_STYLES',
        'USER_PREFERENCES_SYNC_DEEP_VARIABLES',
        'PREVIEW_LOCK_SOURCE_COLORS',
        'PREVIEW_SCORES_WCAG_INTERVAL',
        'PREVIEW_SCORES_APCA_INTERVAL',
        'PREVIEW_FILTER_WCAG',
        'PREVIEW_FILTER_APCA',
        'PREVIEW_SHADE_REPORT',
        'DOCUMENT_PALETTE',
        'DOCUMENT_PALETTE_PROPERTIES',
        'DOCUMENT_SHEET',
        'DOCUMENT_PUSH_UPDATES',
        'VIEWS_PALETTE',
        'VIEWS_PALETTE_WITH_PROPERTIES',
        'VIEWS_SHEET',
        'SOURCE',
        'SOURCE_COOLORS_ADD',
        'SOURCE_REALTIME_COLORS_ADD',
        'SOURCE_EXPLORE_ADD',
        'SOURCE_AI_REQUEST',
        'SOURCE_IMAGE_UPLOAD',
        'SOURCE_HARMONY_BASE',
        'SOURCE_HARMONY_ADD',
        'SOURCE_EXPLORE_ADD',
        'PRESETS_MATERIAL',
        'PRESETS_MATERIAL_3',
        'PRESETS_TAILWIND',
        'PRESETS_RADIX',
        'PRESETS_UNTITLED_UI',
        'PRESETS_SPECTRUM',
        'PRESETS_SPECTRUM_NEUTRAL',
        'PRESETS_ADS',
        'PRESETS_ADS_NEUTRAL',
        'PRESETS_CARBON',
        'PRESETS_BASE',
        'PRESETS_FLUENT',
        'PRESETS_POLARIS',
        'PRESETS_CUSTOM_ADD',
        'SCALE_CONTRAST_RATIO',
        'SCALE_CHROMA',
        'SCALE_HUE',
        'THEMES',
        'THEMES_NAME',
        'THEMES_PARAMS',
        'THEMES_DESCRIPTION',
        'COLORS',
        'COLORS_HUE_SHIFTING',
        'COLORS_CHROMA_SHIFTING',
        'COLORS_ALPHA',
        'COLORS_BACKGROUND_COLOR',
        'EXPORT_STYLESHEET_SCSS',
        'EXPORT_STYLESHEET_LESS',
        'EXPORT_TAILWIND_V3',
        'EXPORT_TAILWIND_V4',
        'EXPORT_APPLE_SWIFTUI',
        'EXPORT_APPLE_UIKIT',
        'EXPORT_ANDROID_COMPOSE',
        'EXPORT_ANDROID_XML',
        'EXPORT_CSV',
        'SETTINGS_COLOR_SPACE_OKLCH',
        'SETTINGS_COLOR_SPACE_LAB',
        'SETTINGS_COLOR_SPACE_OKLAB',
        'SETTINGS_COLOR_SPACE_HSLUV',
        'SETTINGS_VISION_SIMULATION_MODE_PROTANOPIA',
        'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOMALY',
        'SETTINGS_VISION_SIMULATION_MODE_DEUTERANOPIA',
        'SETTINGS_VISION_SIMULATION_MODE_TRITANOMALY',
        'SETTINGS_VISION_SIMULATION_MODE_TRITANOPIA',
        'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOMALY',
        'SETTINGS_VISION_SIMULATION_MODE_ACHROMATOPSIA',
        'SETTINGS_ALGORITHM_V1',
        'SETTINGS_ALGORITHM_V2',
        'SETTINGS_TEXT_COLORS_THEME',
        'HELP_EMAIL',
      ],
      ['INVOLVE_COMMUNITY']
    ),
  },
}

const globalConfig: Config = {
  limits: {
    pageSize: 20,
    width: 640,
    height: 640,
    minWidth: 240,
    minHeight: 420,
    localPalettes: 1,
    sourceColors: 5,
    customStops: 8,
  },
  env: {
    platform: 'figma',
    editor: 'figma',
    ui: 'figma',
    colorMode: 'figma-dark',
    isDev,
    isSupabaseEnabled: true,
    isMixpanelEnabled: true,
    isSentryEnabled: true,
    isMistralAiEnabled: true,
    announcementsDbId: import.meta.env.VITE_NOTION_ANNOUNCEMENTS_ID as string,
    onboardingDbId: import.meta.env.VITE_NOTION_ONBOARDING_ID as string,
    pluginId: specConfig[__PLUGIN__].pluginId,
  },
  plan: {
    isProEnabled: true,
    isTrialEnabled: false,
    isCreditsEnabled: true,
    trialTime: 72,
    creditsLimit: 500,
    creditsRenewalPeriodDays: 7,
    creditsRenewalPeriodHours: 168,
  },
  dbs: {
    palettesDbViewName: isDev
      ? 'sandbox_palettes_with_creators'
      : 'palettes_with_creators',
    palettesDbTableName: isDev ? 'sandbox_palettes' : 'palettes',
    starredPalettesDbTableName: 'starred_palettes',
  },
  urls: {
    authWorkerUrl: isDev
      ? 'http://localhost:8787'
      : (import.meta.env.VITE_AUTH_WORKER_URL as string),
    announcementsWorkerUrl: isDev
      ? 'http://localhost:8888'
      : (import.meta.env.VITE_ANNOUNCEMENTS_WORKER_URL as string),
    corsWorkerUrl: isDev
      ? 'http://localhost:8989'
      : (import.meta.env.VITE_CORS_WORKER_URL as string),
    databaseUrl: import.meta.env.VITE_SUPABASE_URL as string,
    authUrl: isDev
      ? 'http://localhost:3000'
      : (import.meta.env.VITE_AUTH_URL as string),
    storeApiUrl: import.meta.env.VITE_LEMONSQUEEZY_URL as string,
    platformUrl: 'https://www.figma.com',
    uiUrl: isDev
      ? 'http://localhost:4400'
      : 'https://figma.ui-color-palette.com',
    documentationUrl: 'https://uicp.ylb.lt/docs-figma-plugin',
    repositoryUrl: 'https://uicp.ylb.lt/repository-figma-plugin',
    communityUrl: 'https://uicp.ylb.lt/community',
    supportEmail: 'https://uicp.ylb.lt/contact',
    feedbackUrl: 'https://uicp.ylb.lt/feedback',
    trialFeedbackUrl: 'https://uicp.ylb.lt/feedback-trial',
    requestsUrl: 'https://uicp.ylb.lt/ideas',
    networkUrl: 'https://uicp.ylb.lt/network',
    authorUrl: 'https://uicp.ylb.lt/author',
    licenseUrl: 'https://uicp.ylb.lt/license',
    privacyUrl: 'https://uicp.ylb.lt/privacy',
    vsCodeFigmaPluginUrl: 'https://uicp.ylb.lt/vscode-figma-plugin',
    isbUrl: 'https://isb.ylb.lt/website',
    uicpUrl: 'https://uicp.ylb.lt/website',
    storeManagementUrl: 'https://uicp.ylb.lt/store-management',
    storeProWeekUrl: 'https://uicp.ylb.lt/pro-week',
    storeProMonthUrl: 'https://uicp.ylb.lt/pro-month',
    storeProYearUrl: 'https://uicp.ylb.lt/pro-year',
    storeProLifetimeUrl: 'https://uicp.ylb.lt/pro-lifetime',
    storeUltimateRequestUrl: 'https://uicp.ylb.lt/ultimate-request',
    howToUseUrl: 'https://uicp.ylb.lt/how-to-use-figma',
  },
  versions: {
    userConsentVersion: '2025.09',
    trialVersion: '2024.03',
    algorithmVersion: 'v3',
    paletteVersion: '2025.06',
    pluginVersion: __APP_VERSION__,
    creditsVersion: '2026.02.02',
  },
  features: specConfig[__PLUGIN__].features,
  lang: 'en-US',
  fees: {
    colourLoversImport: 25,
    coolorsImport: 25,
    realtimeColorsImport: 25,
    imageColorsExtract: 50,
    harmonyCreate: 50,
    aiColorsGenerate: 50,
    paletteGenerate: 150,
    paletteWithPropsGenerate: 200,
    sheetGenerate: 250,
    paletteUpdates: 25,
    localStylesSync: 250,
    localVariablesSync: 300,
  },
}

const limitsMapping: { [key: string]: keyof typeof globalConfig.limits } = {
  LOCAL_PALETTES: 'localPalettes',
  SOURCE: 'sourceColors',
  COLORS: 'sourceColors',
  PRESETS_CUSTOM_ADD: 'customStops',
}

globalConfig.features.forEach((feature) => {
  const limitKey = limitsMapping[feature.name]
  if (limitKey && globalConfig.limits[limitKey] !== undefined)
    feature.limit = globalConfig.limits[limitKey]
})

export default globalConfig
