name: Build and Download UI Color Palette

on: workflow_dispatch

env:
  REACT_APP_SUPABASE_PUBLIC_ANON_KEY: ${{ secrets.SUPABASE_PUBLIC_ANON_KEY }}
  

jobs:
  build:
    name: Build with Node
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Dotenv
      uses: mikeal/actions-dotenv@v1
      with:
        path: .env

    - name: Install and Build
      run: |
        npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        npm install
        npm run build:prod
    
    - name: Archive production artifact
      uses: actions/upload-artifact@v4
      with:
        name: figma-ui-color-palette
        path: |
          dist
          manifest.json
        retention-days: 5
