name: Build and Download UI Color Palette

on: workflow_dispatch

jobs:
  build:
    name: Build with Node
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: 'Create .env file'
      run: |
        touch .env
        echo REACT_APP_NOTION_API_KEY="${{ secrets.NOTION_API_KEY }}" >> .env
        echo REACT_APP_SUPABASE_PUBLIC_ANON_KEY="${{ secrets.SUPABASE_PUBLIC_ANON_KEY }}" >> .env
        echo REACT_APP_NOTION_TRIAL_TABLE_ID="${{ vars.NOTION_TRIAL_TABLE_ID }}" >> .env
        cat .env

    - name: Install and Build
      run: |
        npm install
        npm run build:prod
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: figma-ui-color-palette
        path: |
          dist
          manifest.json
        retention-days: 5
