name: Build and Download UI Color Palette

on: workflow_dispatch

jobs:
  build-plugin:
    name: Build with Node
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Initialize and update submodules
      run: |
        git submodule update --init --recursive --force

    - name: Create .env.local file
      run: |
        touch .env.local
        echo VITE_SUPABASE_URL="${{ vars.VITE_SUPABASE_URL }}" >> .env.local
        echo VITE_SUPABASE_PUBLIC_ANON_KEY="${{ secrets.VITE_SUPABASE_PUBLIC_ANON_KEY }}" >> .env.local
        echo VITE_SENTRY_DSN="${{ vars.VITE_SENTRY_DSN }}" >> .env.local
        echo VITE_MIXPANEL_TOKEN="${{ secrets.VITE_MIXPANEL_TOKEN }}" >> .env.local
        echo VITE_AUTH_WORKER_URL="${{ vars.VITE_AUTH_WORKER_URL }}" >> .env.local
        echo VITE_AUTH_URL="${{ vars.VITE_AUTH_URL }}" >> .env.local
        echo VITE_ANNOUNCEMENTS_WORKER_URL="${{ vars.VITE_ANNOUNCEMENTS_WORKER_URL }}" >> .env.local
        echo VITE_NOTION_ANNOUNCEMENTS_ID="${{ vars.VITE_NOTION_ANNOUNCEMENTS_ID }}" >> .env.local
        echo VITE_NOTION_ONBOARDING_ID="${{ vars.VITE_NOTION_ONBOARDING_ID }}" >> .env.local
        cat .env.local
        touch .env.sentry-build-plugin
        echo SENTRY_AUTH_TOKEN="${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env.sentry-build-plugin
        cat .env.sentry-build-plugin

    - name: Clean install
      run: |
        rm -rf node_modules package-lock.json

    - name: Install and Build
      run: |
        npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        npm install
        npm run build:prod

    - name: Archive production artifact
      uses: actions/upload-artifact@v4
      with:
        name: figma-ui-color-palette
        path: |
          dist
          manifest.json
        retention-days: 5
